name: cobra
version: 0.0.1
description: Cobra is a http annotation framwork.
author: wyndam <only.night@qq.com>
homepage: http://github.com/onlynight/Cobra

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.11.3
